name: Release QuakeLogparser

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  build:
    name: GoReleaser ParseQuakeLog
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags

      - name: Set up Go 1.18
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          args: release --clean
          workdir: cmd/parse_quake_log
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
